// This file is auto-generated by @hey-api/openapi-ts

export const $AuthResponse = {
  description: "Successful authentication response",
  example: {
    token: "vW4sIvFvqkw6iogdhNyyFXa2nKg4LlsVobOTR721hbs",
    token_type: "bearer",
  },
  properties: {
    token: {
      description: "Token",
      type: "string",
    },
    token_type: {
      description: "Token Type",
      type: "string",
    },
  },
  required: ["token", "token_type"],
  title: "AuthResponse",
  type: "object",
} as const;

export const $Bot = {
  description: "Schema for a Bot",
  example: {
    id: 1,
    name: "Example Bot",
    package_json: "{}",
    script: "console.log('Hello, world!')",
  },
  properties: {
    id: {
      description: "Bot ID",
      type: "integer",
    },
    name: {
      description: "Unique bot name",
      type: "string",
    },
    package_json: {
      description: "Package JSON of the bot",
      type: "string",
    },
    script: {
      description: "Script of the bot",
      type: "string",
    },
  },
  required: ["name", "package_json", "script", "start_command"],
  title: "Bot",
  type: "object",
} as const;

export const $BotDeployParams = {
  description: "Schema for deploying a Bot",
  example: {
    name: "Example Bot",
    package_json: "{}",
    script: "console.log('Hello, world!')",
  },
  properties: {
    name: {
      description: "Name of the bot",
      type: "string",
    },
    package_json: {
      description: "Package JSON of the bot",
      type: "string",
    },
    script: {
      description: "Script of the bot",
      type: "string",
    },
  },
  required: ["name", "package_json", "script"],
  title: "BotDeployParams",
  type: "object",
} as const;

export const $BotList = {
  description: "List of Bots",
  example: [
    {
      id: 1,
      name: "Example Bot",
      package_json: "{ name: 'Example Bot' }",
      script: "console.log('Hello, world!')",
    },
    {
      id: 2,
      name: "Example Bot 2",
      package_json: "{ name: 'Example Bot 2' }",
      script: "console.log('Hello, world!')",
    },
  ],
  items: {
    $ref: "#/components/schemas/Bot",
  },
  title: "BotList",
  type: "array",
} as const;

export const $BotRun = {
  description: "Trigger a Bot run",
  example: {
    bot_id: 1,
    id: "223e4567-e89b-12d3-a456-426614174001",
    inserted_at: "2023-06-15T11:00:00Z",
    params: {
      param1: "value3",
      param2: "value4",
    },
    result: "running",
  },
  properties: {
    bot_id: {
      description: "Bot ID",
      type: "integer",
    },
    id: {
      description: "Bot run ID",
      type: "string",
    },
    inserted_at: {
      description: "Timestamp when the run was created",
      type: "string",
    },
    params: {
      description: "Params used for the Bot run",
      type: "map",
    },
    result: {
      description: "Result of the Bot run",
      type: "string",
    },
  },
  required: ["bot_id", "params"],
  title: "BotRun",
  type: "object",
} as const;

export const $BotRunList = {
  description: "A list of Bot runs",
  example: [
    {
      bot_id: 1,
      id: "123e4567-e89b-12d3-a456-426614174000",
      inserted_at: "2023-06-15T10:00:00Z",
      params: {
        param1: "value1",
        param2: "value2",
      },
      result: "success",
    },
    {
      bot_id: 1,
      id: "223e4567-e89b-12d3-a456-426614174001",
      inserted_at: "2023-06-15T11:00:00Z",
      params: {
        param1: "value3",
        param2: "value4",
      },
      result: "running",
    },
  ],
  items: {
    $ref: "#/components/schemas/BotRun",
  },
  title: "BotRunList",
  type: "object",
} as const;

export const $BotRunParams = {
  description: "Parameters for triggering a Bot run",
  example: {
    params: {
      key1: "value1",
      key2: "value2",
      key3: "value3",
    },
  },
  properties: {
    params: {
      additionalProperties: {
        type: "string",
      },
      description: "Optional key-value pairs of parameters for the Bot run",
      type: "object",
    },
  },
  title: "BotRunParams",
  type: "object",
} as const;

export const $BotRunStatus = {
  description: "Status of a Bot run including run details and logs",
  example: {
    logs: [
      {
        level: "info",
        msg: "Bot run started",
        timestamp: "2023-06-15T11:00:01Z",
      },
      {
        level: "debug",
        msg: "Processing input parameters",
        timestamp: "2023-06-15T11:00:02Z",
      },
    ],
    run: {
      bot_id: 1,
      id: "223e4567-e89b-12d3-a456-426614174001",
      inserted_at: "2023-06-15T11:00:00Z",
      params: {
        param1: "value3",
        param2: "value4",
      },
      result: "running",
    },
  },
  properties: {
    logs: {
      description: "List of logs for the Bot run",
      items: {
        properties: {
          level: {
            description: "Log level",
            enum: ["info", "debug"],
            type: "string",
          },
          msg: {
            description: "Log message",
            type: "string",
          },
          timestamp: {
            description: "Timestamp when the log was created",
            format: "date-time",
            type: "string",
          },
        },
        required: ["level", "msg", "timestamp"],
        type: "object",
      },
      type: "array",
    },
    run: {
      $ref: "#/components/schemas/BotRun",
    },
  },
  required: ["run", "logs"],
  title: "BotRunStatus",
  type: "object",
} as const;

export const $UserCredentials = {
  description: "Request body for user credentials",
  example: {
    email: "admin@example.com",
    password: "password",
  },
  properties: {
    email: {
      description: "Email address",
      format: "email",
      type: "string",
    },
    password: {
      description: "Password",
      format: "password",
      type: "string",
    },
  },
  required: ["name", "email"],
  title: "UserCredentials",
  type: "object",
} as const;
