// This file is auto-generated by @hey-api/openapi-ts

/**
 * Successful authentication response
 */
export type AuthResponse = {
  /**
   * Token
   */
  token: string;
  /**
   * Token Type
   */
  token_type: string;
};

/**
 * Schema for a Bot
 */
export type Bot = {
  /**
   * Bot ID
   */
  id?: number;
  /**
   * Unique bot name
   */
  name: string;
  /**
   * Package JSON of the bot
   */
  package_json: string;
  /**
   * Script of the bot
   */
  script: string;
};

/**
 * Schema for deploying a Bot
 */
export type BotDeployParams = {
  /**
   * Name of the bot
   */
  name: string;
  /**
   * Package JSON of the bot
   */
  package_json: string;
  /**
   * Script of the bot
   */
  script: string;
};

/**
 * List of Bots
 */
export type BotList = Array<Bot>;

/**
 * Trigger a Bot run
 */
export type BotRun = {
  /**
   * Bot ID
   */
  bot_id: number;
  /**
   * Bot run ID
   */
  id?: string;
  /**
   * Timestamp when the run was created
   */
  inserted_at?: string;
  /**
   * Params used for the Bot run
   */
  params: {
    [key: string]: string;
  };
  /**
   * Result of the Bot run
   */
  result?: string;
};

/**
 * A list of Bot runs
 */
export type BotRunList = {
  [key: string]: unknown;
};

/**
 * Parameters for triggering a Bot run
 */
export type BotRunParams = {
  /**
   * Optional key-value pairs of parameters for the Bot run
   */
  params?: {
    [key: string]: string;
  };
};

/**
 * Status of a Bot run including run details and logs
 */
export type BotRunStatus = {
  /**
   * List of logs for the Bot run
   */
  logs: Array<{
    /**
     * Log level
     */
    level: "info" | "debug";
    /**
     * Log message
     */
    msg: string;
    /**
     * Timestamp when the log was created
     */
    timestamp: Date;
  }>;
  run: BotRun;
};

/**
 * Request body for user credentials
 */
export type UserCredentials = {
  /**
   * Email address
   */
  email: string;
  /**
   * Password
   */
  password?: string;
};

export type ListBotsResponse = BotList;

export type ListBotsError = {
  [key: string]: unknown;
};

export type DeployBotData = {
  /**
   * Bot Params
   */
  body: BotDeployParams;
};

export type DeployBotResponse = Bot;

export type DeployBotError = {
  [key: string]: unknown;
} & unknown;

export type DeleteBotData = {
  path: {
    /**
     * Bot ID
     */
    id: number;
  };
};

export type DeleteBotResponse = void;

export type DeleteBotError = {
  [key: string]: unknown;
} & unknown;

export type ShowBotData = {
  path: {
    /**
     * Bot ID
     */
    id: number;
  };
};

export type ShowBotResponse = Bot;

export type ShowBotError = {
  [key: string]: unknown;
} & unknown;

export type ListBotRunsData = {
  path: {
    /**
     * Bot ID
     */
    id: number;
  };
};

export type ListBotRunsResponse = BotRunList;

export type ListBotRunsError = {
  [key: string]: unknown;
} & unknown;

export type TriggerBotRunData = {
  /**
   * Bot Run Params
   */
  body?: BotRunParams;
  path: {
    /**
     * Bot ID
     */
    id: number;
  };
};

export type TriggerBotRunResponse = BotRun;

export type TriggerBotRunError = {
  [key: string]: unknown;
} & unknown;

export type GetBotRunStatusData = {
  path: {
    /**
     * Bot ID
     */
    id: number;
    /**
     * Run ID
     */
    run_id: string;
  };
};

export type GetBotRunStatusResponse = BotRunStatus;

export type GetBotRunStatusError = {
  [key: string]: unknown;
} & unknown;

export type AuthenticateUserData = {
  /**
   * User credentials
   */
  body?: UserCredentials;
};

export type AuthenticateUserResponse = AuthResponse;

export type AuthenticateUserError = {
  [key: string]: unknown;
};

export type $OpenApiTs = {
  "/api/bot": {
    get: {
      res: {
        /**
         * Bot List Response
         */
        "200": BotList;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
      };
    };
    post: {
      req: DeployBotData;
      res: {
        /**
         * Deployed bot
         */
        "200": Bot;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Name already exists
         */
        "409": unknown;
        /**
         * Unprocessable Entity
         */
        "422": {
          [key: string]: unknown;
        };
      };
    };
  };
  "/api/bot/{id}": {
    delete: {
      req: DeleteBotData;
      res: {
        /**
         * Bot Deleted
         */
        "204": void;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Not Found
         */
        "404": unknown;
      };
    };
    get: {
      req: ShowBotData;
      res: {
        /**
         * Bot Details
         */
        "200": Bot;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Not Found
         */
        "404": unknown;
      };
    };
  };
  "/api/bot/{id}/run": {
    get: {
      req: ListBotRunsData;
      res: {
        /**
         * Bot Runs
         */
        "200": BotRunList;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Not Found
         */
        "404": unknown;
      };
    };
    post: {
      req: TriggerBotRunData;
      res: {
        /**
         * Bot Run
         */
        "200": BotRun;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Not Found
         */
        "404": unknown;
        /**
         * Unprocessable Entity
         */
        "422": {
          [key: string]: unknown;
        };
      };
    };
  };
  "/api/bot/{id}/run/{run_id}": {
    get: {
      req: GetBotRunStatusData;
      res: {
        /**
         * Bot Run Status
         */
        "200": BotRunStatus;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
        /**
         * Not Found
         */
        "404": unknown;
      };
    };
  };
  "/api/login": {
    post: {
      req: AuthenticateUserData;
      res: {
        /**
         * Authenticated response
         */
        "200": AuthResponse;
        /**
         * Unauthorised
         */
        "401": {
          [key: string]: unknown;
        };
      };
    };
  };
};
